name: tio_world

packages:
  - apps/app
  - apps/wear
  - apps/shared
  - apps/core
  - apps/features/**

scripts:
  bootstrap:
    run: melos bootstrap
    description: Bootstrap all Flutter and Dart packages in the workspace.

  get:
    run: melos exec -- "flutter pub get"
    description: Run 'flutter pub get' in all packages.

  analyze:
    run: melos exec -- "flutter analyze"
    description: Run 'flutter analyze' in all packages.

  analyze:dart:
    run: melos exec --scope="tio_shared" -- "dart analyze"
    description: Analyze pure Dart shared package.

  test:
    run: melos exec --dir-exists="test" -- "flutter test"
    description: Run 'flutter test' in all packages that have a test directory.

  app:run:
    run: cd apps/app && flutter run
    description: Run the phone app.

  wear:run:
    run: cd apps/wear && flutter run
    description: Run the Wear OS app.
