name: tio_world_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  tio_core:
    path: apps/core
  tio_shared:
    path: apps/shared

dev_dependencies:
  flutter_lints: ^6.0.0
