import 'package:flutter/material.dart';

import '../primitive/tio_alpha.dart';

class TioDialogTokens {
  const TioDialogTokens._();

  static const otpInsetHorizontal = 32.0;
  static const otpPanelTopPadding = 28.0;
  static const otpPanelRadius = 28.0;
  static const otpPanelOutlineAlpha = TioAlpha.alpha30;
  static const otpShadowColor = Color(0x50000000);
  static const otpShadowBlurRadius = 30.0;
  static const otpShadowOffsetY = 10.0;
  static const otpTitleFontSize = 16.0;
  static const otpTitleLetterSpacing = -0.2;
  static const otpTitleToInputGap = 18.0;
  static const otpInputHeight = 52.0;
  static const otpInputRadius = 26.0;
  static const otpErrorOutlineAlpha = TioAlpha.alpha90;
  static const otpInputOutlineAlpha = TioAlpha.alpha40;
  static const otpInputHorizontalPadding = 20.0;
  static const otpInputFontSize = 20.0;
  static const otpInputLetterSpacing = 6.0;
  static const otpErrorFontSize = 12.0;
  static const otpSubtitleTopGap = 14.0;
  static const otpSubtitleFontSize = 13.0;
  static const otpSubtitleLineHeight = 1.35;
  static const otpVerifyTopGap = 22.0;
  static const otpActionRadius = 20.0;
  static const otpActionHorizontalPadding = 28.0;
  static const otpActionContainerAlpha = TioAlpha.alpha40;
  static const otpLoadingSize = 18.0;
  static const otpLoadingStrokeWidth = 2.0;
  static const otpActionFontSize = 13.0;
  static const otpActionLetterSpacing = 0.8;
  static const otpBackTopGap = 14.0;

  static const deleteHoldFillColor = Color(0xFFE55757);
  static const deleteHoldContentColor = Color(0xFFFFFFFF);
  static const deleteOverlayBackgroundAlpha = TioAlpha.alpha245;
  static const deleteCloseButtonSize = 36.0;
  static const deleteCloseContainerAlpha = TioAlpha.alpha25;
  static const deleteCloseIconSize = 20.0;
  static const deleteCloseSplashRadius = 18.0;
  static const deleteHeadlineFontSize = 28.0;
  static const deleteHeadlineLetterSpacing = -0.5;
  static const deleteBodyFontSize = 16.0;
  static const deleteBodyLineHeight = 1.4;
  static const deleteWarningFontSize = 14.0;
  static const deleteActionSectionGap = 36.0;
  static const deleteActionButtonHeight = 54.0;
  static const deleteActionButtonRadius = 27.0;
  static const deleteActionLabelFontSize = 16.0;
  static const deleteActionContainerAlpha = TioAlpha.alpha35;
  static const deleteHoldHeadlineLineHeight = 1.25;
  static const deleteHoldBodyFontSize = 15.0;
  static const deleteHoldControlTopGap = 48.0;
  static const deleteCountdownHeight = 44.0;
  static const deleteCountdownFontSize = 34.0;
  static const deleteHoldControlSize = 140.0;
  static const deleteHoldStrokeWidth = 6.0;
  static const deleteHoldTrackAlpha = TioAlpha.alpha25;
  static const deleteHoldButtonSize = 100.0;
  static const deleteHoldGlowAlpha = TioAlpha.alpha80;
  static const deleteHoldGlowBlurRadius = 20.0;
  static const deleteHoldGlowSpreadRadius = 2.0;
  static const deleteHoldLoadingStrokeWidth = 2.5;
  static const deleteHoldActionGap = 56.0;
  static const deleteCompletedIconContainerSize = 72.0;
  static const deleteCompletedIconContainerAlpha = TioAlpha.alpha30;
  static const deleteCompletedIconSize = 38.0;
  static const deleteCompletedIconGap = 20.0;
  static const deleteCompletedTitleFontSize = 24.0;
  static const deleteCompletedTextGap = 10.0;
  static const deleteCompletedBodyFontSize = 14.0;
  static const deleteCompletedBodyLineHeight = 1.35;
}
