name: tio_feature_welcome
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  flutter_svg: ^2.2.0
  tio_core:
    path: ../../core
  tio_shared:
    path: ../../shared

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/landing_screen.png
    - assets/dumbell-blue.png
    - assets/ic_chat.svg
