name: tio_core
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  image_picker: ^1.1.2
  tio_shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/nav_icon/
    - assets/image/
    - assets/image/equipments/
    - assets/svg_icon/
